### ISSUE TITLE
 How to disable the issuance of articles from the GeoJson namespace by randomepage?

### ISSUE THREAD

**Issue by RogueVortex** [ProfessionalWiki/Maps#705]
I've run into a lot of questions from users when they use mediawiki's standard random article feature to stumble upon articles in the GeoJson namespace.
Are there ways to disable or hide them?

I tried following the instructions in this article and nothing helped ....
https://www.mediawiki.org/wiki/Manual:$wgContentNamespaces

**Comment by JeroenDeDauw** [comment]
The namespace is marked as a content namespace at https://github.com/ProfessionalWiki/Maps/blob/master/extension.json#L49

**Comment by JeroenDeDauw** [comment]
Changing that line to `false` will presumably fix your issue, though I am not 100% sure it will not break the GeoJSON functionality in some manner. Since you are apparently using said functionality, could you try out that change for a bit, and then report back? If it works well, we can apply the change to the canonical version of the extension.

**Comment by RogueVortex** [comment]
It seems the issue has been resolved, for more than 200 transitions through the random page, an article from the GeoJson namespace has never been opened, also articles from this namespace are not searched through the mediawiki search and this is very cool, thank you very much for your help

Map container articles using GeoJson work flawlessly
